### ISSUE TITLE
Provide a .war file with release

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#19]
**Tasks:**
- [x] Get a working WAR from M6 release (pre-Orion).
- [x] Manually create WAR from nightlies (post-Orion).
- [ ] Fix build to output WAR file.

**Comment by JonFerraiolo** [comment]
@jhpedemonte @childsb 

@peller: our build scripts produce a .war file today. Are you saying we should post a .war file next to the .zip file that we post at maqetta.org/downloads? If so, I would say don't bother. Anyone who wants a .war file probably is a Java geek, and they can build their own .war file.

**Comment by jhpedemonte** [comment]
Also, moving to Orion build, which doesn't produce a WAR file at all.

**Comment by peller** [comment]
People were asking for it, since it made sense at the time to be able run our servlet on other servers.  It's not unreasonable for someone to expect us to post the results of the build script.  If our Orion configuration makes a war meaningless, I'm happy to close this issue.

**Comment by peller** [comment]
see a13ae6347a7b3863ce0a6aa12e3aebc13fb8ba0b

**Comment by jhpedemonte** [comment]
Here's what I had to do to manually create a working M9 WAR:
1. Built a WAR file from the [M6-war branch](https://github.com/maqetta/maqetta/compare/master...M6-war).
2. Built an M9 nightly from the [orion-war branch](https://github.com/maqetta/maqetta/compare/master...orion-war) (no WAR is built, just a regular standalone build).
3. In the WAR, copy in the following files:
   - Replace all of `/WEB-INF/plugins/` with those from the M9 nightly, but keep:
     - _org.eclipse.equinox.http.servletbridge_
     - _org.eclipse.equinox.servletbridge.extensionbundle_
   - Replace all of `/WEB-INF/features/` with those from the M9 nightly, but keep:
     - _org.eclipse.equinox.server.servletbridge_
     - _org.eclipse.equinox.server.core_
   - Replace all of `/WEB-INF/configuration/` with same directory from M9 nightly.
4. In the WAR, Replace the _web.xml_ file with [this one](https://github.com/maqetta/maqetta/blob/war-build/maqetta.war/rootfiles/web.xml).
5. In the WAR, Edit `/WEB-INF/plugins/org.eclipse.equinox.servletbridge.extensionbundle/META-INF/MANIFEST.MF` to export v2.6 of _javax.servlet._\* namespaces, and to export more of those namespaces.  See [patch](https://gist.github.com/4636506).
6. In the WAR, Edit `/WEB-INF/configuration/org.eclipse.equinox.simpleconfigurator/bundle.info`:
   - Comment out the 2 `javax.servlet` entries.
   - Find `http.registry` and change the `false` at the end of the line to `true`.
   - Add the following lines to the end of the file:
     
     ```
     org.eclipse.equinox.http.servletbridge,1.0.200.201301171751,plugins/org.eclipse.equinox.http.servletbridge_1.0.200.201301171751.jar,2,true
     org.eclipse.equinox.servletbridge.extensionbundle,1.2.0.201301171751,plugins/org.eclipse.equinox.servletbridge.extensionbundle_1.2.0.201301171751.jar,4,false
     ```

---

To update an M9 WAR with the latest code from a nightly, just repeat steps 3 & 6.

**Comment by billreed63** [comment]
#3702 change theme editor to use relative url

**Comment by jhpedemonte** [comment]
Adding long strings of "../../../.." to handle URLs is inconvenient.  A couple of options come to mind:
1. Make the standalone, Jetty-based build also have a "/maqetta" context, such that all URLs start with that (including the Orion ones -- not sure how that would work out).  This would also have the benefit of removing the "/maqetta/maqetta/..." duplication we have now.
2. Make the context variable, such that the server could determine if URLs require the added context when running from a WAR.  This means that the server would have to do substitutions on HTML files (would be cached).  For JS files, we could set it in one file and have all the others query the context info from that main file.

**Comment by jhpedemonte** [comment]
Also see commits 47bcb545fd2a621af7ac318ced50afee1a7d6381, 9d2b7ea6d0fbf491bcfa4f5b2615d5e04a57388b, 6907d51776242fdb432145798b2c76319a09cef7, 9d0e7b53c5e5cb3dcd09c33dc91674bc03c70c4b.

**Comment by peller** [comment]
The war is working, more or less, but must be built manually.  @jhpedemonte will work on automating this in M10

-> M10

**Comment by peller** [comment]
still not automated, but should be possible based on latest Orion

-> future
