### ISSUE TITLE
Upgrade to Orion v1.0

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3481]
**Tasks**
- [x] Update use of Java APIs.
- [x] Do we need to make any changes based on Orion's [new file URL](https://bugs.eclipse.org/bugs/show_bug.cgi?id=343264).
- [x] Update Maqetta auth plugins based on changes to that of Orion (including changes to LoginWindow.\* files).
- [x] Handle new required `login` field for auth server APIs.
- [x] Change to use Orion's `UserEmailUtil` and config props (get rid of Maqetta's `smtp.mailServer`, etc)
- [x] Test reset password support (requires email support).
- [x] Investigate `CONFIG_AUTH_USER_CREATION_FORCE_EMAIL`.
- ~~[ ] Replace Orion's email templates for registration, password reset, etc.~~ ==> #3846
- ~~[ ] Need to revert workarounds commited in #3374, particularly instances of `result.parent().flush()` (should just be `result.flush()`).~~ ==> Orion code still has this workaround, so we'll keep it in place also.
- ~~[ ] Make use of Orion filters: AuthorizedUserFilter/LoggedInUserFilter (see f60fc5987d9865c7b7af5e2fb1bb4ce00e228925), CacheFilter, GzipFilter (?)~~ ==> #3901 
- [x] Add support for 'server messages on login pages' ([info](http://wiki.eclipse.org/Orion/Server_admin_guide#Server_Messages_on_Login_Page))
- ~~[ ] Our code invoked `sendMail` in a `Runnable`, putting it on a separate thread (see old _ResetPassword.java_).  Orion does not -- could this be a performance issue?~~
- [x] Make sure Unix/OS X startup scripts are executable.

**Comment by jhpedemonte** [comment]
Looked over the [diff of changed between Orion 0.5 & 1.0](https://github.com/eclipse/orion.server/compare/R0_5...R1_0) -- here are some notable changes which could impact us or which we could take advantage of:
- Orion now displays a user's workspace using a [new path format](https://bugs.eclipse.org/bugs/show_bug.cgi?id=343264): `/file/{workspaceId}/{projectName}[/{path}]`
- `authentication` plugins all merged into one.
  - Some minor changes, as well.
    - Might need to update our custom auth plugin with similar changes.
  - Added Mozilla Persona support.
    - http://wiki.eclipse.org/Orion/Server_admin_guide#Configuring_Mozilla_Persona_authentication
    - Can we get user's email from that? If so, we should support it in Maqetta.
  - What about OpenId? Can get user's email?
- Added `CONFIG_AUTH_USER_CREATION_FORCE_EMAIL`, described like this:
  
  > The name of a configuration property specifying is user email is mandatory while user creation.
  > If <code>true</code> user will be forced to add email while creating account. Account will be blocked
  > until user email is confirmed.
- `WebUser.fromUserName()` -> `WebUser.fromUserId()`
  - `WebUser.getName()` -> `.getId()` in some cases
- Allows "Server Messages on Login Page".  See server admin docs.
- The login server APIs have changed slightly:
  - In 0.5, "/users" and "/login" took two fields: `login`, `password`.  The `login` field had no restrictions and could be an email address.
  - In 1.0, those server APIs now take 3 fields: `login`, `password` and `email` (optional).  The `login` field can only be _alphanumeric_ (see [bug 388521](https://bugs.eclipse.org/bugs/show_bug.cgi?id=388521)).  Also, it's limited to _20 chars max_.
- Updates to [UserEmailUtil.java](https://github.com/eclipse/orion.server/compare/R0_5…R1_0#diff-175), which handles sending emails to a registered user.
  - A new review notification system for Git commits (see [GitCommitHandlerV1.java](https://github.com/eclipse/orion.server/compare/R0_5…R1_0#diff-112)).
- [AuthorizationService](https://github.com/eclipse/orion.server/compare/R0_5…R1_0#diff-158) allows setting read/write access to a given URI.

@JonFerraiolo @peller @billreed63

**Comment by JonFerraiolo** [comment]
> What about OpenId? Can get user's email?

Short answer is no. Long answer: When I researched this a couple of months ago, some OpenId hosts provide APIs where you can get the user's emails, and others don't. For Facebook, there is such an API, but a user has to grant permission using a Facebook dialog to grant such permission. I suspect that most systems already do a similar thing as Facebook or will move there once they become more sensitive to security and privacy concerns.

> Added `CONFIG_AUTH_USER_CREATION_FORCE_EMAIL`

All we really need is an email, so **theoretically** `CONFIG_AUTH_USER_CREATION_FORCE_EMAIL` looks promising. However, what's the difference between Orion posting a type-in box to enter an email address and Maqetta posting a type-in box on its login screen that forces the user's ID to be an email address?

Note that for installations on company networks, OpenId and Persona probably won't be allowed.

**Comment by jhpedemonte** [comment]
Also see commit f266a2ea652fef82f65394fd2ee042666c3a298a (update `orion.map` to pull v1.0 code).

**Comment by jhpedemonte** [comment]
[Added an item](https://github.com/maqetta/maqetta/issues/3481#issuecomment-9961872) on changes to the login server APIs.

Basically, in Orion 0.5, the `login` field could take an email address and that is how we used it.  However, for 1.0, they changed it so `login` can only contain **alphanumeric** passwords and thus cannot be an email address.  In order to handle that, they added an optional `email` field.

This changes how we do our login for Maqetta.  I'd love to keep it as just email/password, but the changes in Orion 1.0 will force us to also add a user name.

Then there's the issue of how we handle the existing users, who do not have a `login` field associated with their account.  I'll have to ask the Orion guys if they did any sort of migration.

---

Also, I found out that you cannot **only** use OpenId/Persona to log in to Orion.  You must first have an Orion account (requiring login/password), to which you can associate an "external" OpenId/Persona account.  Then you can login with those.  So these don't really give us anything.

**Comment by jhpedemonte** [comment]
-> M9

**Comment by peller** [comment]
->M10

**Comment by jhpedemonte** [comment]
Note: UserEmailUtil.java always enables TLS support in Orion v1.0 (see [bug 392529](https://bugs.eclipse.org/bugs/show_bug.cgi?id=392529)).  Orion v2.0 made this configurable.

**Comment by jhpedemonte** [comment]
Merged branch **orion_1_0_3481** into **master**.

**Comment by jhpedemonte** [comment]
Closing.  All issues fixed or moves to separate bugs.
