### ISSUE TITLE
Upgrade to Orion v2.0

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3759]
Server changes between [Orion v1.0 & v2.0](http://git.eclipse.org/c/orion/org.eclipse.orion.server.git/diff/?id=R2_0&id2=R1_0)
Client changes between [Orion v1.0 & v2.0](http://git.eclipse.org/c/orion/org.eclipse.orion.client.git/diff/?id=R2_0&id2=R1_0)

Orion v1.0 bug: [#3481](https://github.com/maqetta/maqetta/issues/3481)

**Tasks:**
- [x] Fix errors due to WorkspaceResourceHandler API changes.
- [x] Revert email patch for bug in Orion 1.0 (see e499d7245f8d3f1244db52d881fd5e293d5da957, fixed by [this commit](https://github.com/eclipse/orion.server/commit/a253c98a3bcd921cb7e9d557a59444e3ddd7c37f#bundles/org.eclipse.orion.server.useradmin/src/org/eclipse/orion/server/useradmin/servlets/EmailConfirmationServlet.java))
- [x] Update build to use correct base builder branch

**Comment by peller** [comment]
@yoavrubin

**Comment by yoavrubin** [comment]
Used Maqetta with Orion 2.0. One change I needed to do is in 
maqetta.server.orion.VOrionWorkspaceStorage , line 64 
from WorkspaceResourceHandler.computeProjectLocation(project, null, userName, true); 
to    WorkspaceResourceHandler.computeProjectLocation(null, project, userName, true);

**Comment by jhpedemonte** [comment]
Significant changes:
- Changes to `WorkspaceResourceHandler` API
  - `toJSON()`
  - `computeProjectLocation()`
- Branch change for base builder in `releng/org.eclipse.orion.releng/builder/scripts/masterBuild.sh`
- Removed Dojo dependencies (org.dojotookit bundle).
