### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#3822]
Need to create automated tests for Maqetta server and client.

Best solution is to follow Orion's lead, which uses **JUnit** for testing the Java server and **js-test-driver** for running JavaScript tests against the client code.

References:
- [Orion - Running the tests](http://wiki.eclipse.org/Orion/Running_the_tests)
- [Orion - Writing JS Unit Tests](http://wiki.eclipse.org/Orion/JS_Unit_Test)
- [Orion - How to run Releng JUnit Tests](http://wiki.eclipse.org/Orion/How_Tos/How_To_Run_Releng_JUnits)

---

**Tasks:**
- [ ] Run Orion tests.  This is a good place to start, to get setup.  Plus, we ship with our own plugins and interface with Orion, so we should be testing it as well.
- [ ] Start adding Maqetta-specific tests for server.
- [ ] Add tests for client.

**Comment by billreed63** [comment]
I am not sure js-test-driver is what we want for the client side
from the  [DesignPrinciples page](https://code.google.com/p/js-test-driver/wiki/DesignPrinciples)
"JsTestDriver is to unit-tests what Selenium is to end-to-end tests. The goal of JS Test Driver is to make JavaScript unit test development as seamless as and easy as Java unit tests."

**Comment by jhpedemonte** [comment]
Right, I'm saying let's use what Orion has in place as the base for our automated testing strategy.  So we use js-test-driver to create our units tests: say, testing the code that loads and parses widget metadata.  On top of this, we can integrate a testing framework like Selenium to do the end-to-end or integration tests.  They are not mutually exclusive.

**Comment by billreed63** [comment]
Correct, but our code is so intertwined I suspect it will be very hard to pull out pieces for UT.
